"""Update BudgetProject2024 Model

Revision ID: a69bf265213c
Revises: cce19d5e91d6
Create Date: 2026-02-01 16:23:12.185225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69bf265213c'
down_revision = 'cce19d5e91d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_projects_2024', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ministry_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('ministry_name', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('agency_code', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('agency_name', sa.String(length=250), nullable=True))
        batch_op.drop_index(batch_op.f('ix_budget_projects_2024_agency_normalized'))
        batch_op.drop_index(batch_op.f('ix_budget_projects_2024_code'))
        batch_op.create_index('idx_agency_code', ['agency_code'], unique=False)
        batch_op.create_index('idx_code_ministry', ['code', 'ministry_code'], unique=False)
        batch_op.create_index('idx_ministry_code', ['ministry_code'], unique=False)
        batch_op.drop_column('ministry')
        batch_op.drop_column('agency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_projects_2024', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agency', sa.VARCHAR(length=250), nullable=True))
        batch_op.add_column(sa.Column('ministry', sa.VARCHAR(length=250), nullable=True))
        batch_op.drop_index('idx_ministry_code')
        batch_op.drop_index('idx_code_ministry')
        batch_op.drop_index('idx_agency_code')
        batch_op.create_index(batch_op.f('ix_budget_projects_2024_code'), ['code'], unique=1)
        batch_op.create_index(batch_op.f('ix_budget_projects_2024_agency_normalized'), ['agency_normalized'], unique=False)
        batch_op.drop_column('agency_name')
        batch_op.drop_column('agency_code')
        batch_op.drop_column('ministry_name')
        batch_op.drop_column('ministry_code')

    # ### end Alembic commands ###
