"""Add MinistryAgency model and relationship to SurveyResponse

Revision ID: cce19d5e91d6
Revises: 
Create Date: 2026-02-01 02:56:19.782738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce19d5e91d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ministry_agency_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_survey_response_ministry_agency', 'ministry_agencies', ['ministry_agency_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ministry_agency_id')

    # ### end Alembic commands ###
